
from .stringtables.error import *


ST = {
    # English
    "en": {
        "lang": "en",
        "title": "The Valkyrie Bot",
        "desc": "The Valkyrie Bot | Empowering gaming legends. Forged with Valkyrie spirit. | ..a project by Valky",
        "nav-1": "VALKY BOT",
        "nav-2": "TWITCH BOT",
        "nav-3": "DISCORD BOT",
        "nav-5": "ABOUT",
        "nav-1-1": "Bot Status",
        "nav-1-2": "Tasks, Queued",
        "nav-1-3": "Tasks, Finished",
        "nav-1-4": "Settings, Basic",
        "nav-1-5": "Settings, L.U.N.A.",
        "nav-2-1": "Bot Status",
        "nav-2-2": "Settings, Basic",
        "nav-2-3": "Settings, Scopes",
        "nav-2-4": "Settings, Rewards",
        "nav-3-1": "Bot Status",
        "nav-3-2": "Settings, Basic",
        "nav-5-1": "Valky Dev",
        "nav-5-2": "Buy me a Tea",
        "nav-5-3": "Terms of Service",
        "nav-5-4": "Join Discord",
        "nav-5-5": "Watch on Twitch",
        "nav-5-6": "Logout",
        "foot-1": "2023 © Valky Dev - All rights reserved. This website is intended solely for the purpose of providing information and facilitating communication related to Valky and provided projects.",
        "foot-2": "Terms of Service",
        "foot-3": "Code of Cunduct",
        "foot-4": "Content Usage Policy",
        "foot-5": "CONTACT",
        "foot-6": "TOP",
        "error": EN_ERROR
    },
    # German
    "de": {
        "lang": "de",
        "title": "The Valkyrie Bot",
        "desc": "The Valkyrie Bot | Verstärkung für Gaming-Legenden. Geschmiedet mit Walkürengeist. | ..a project by Valky",
        "nav-1": "VALKY BOT",
        "nav-2": "TWITCH BOT",
        "nav-3": "DISCORD BOT",
        "nav-5": "ÜBER",
        "nav-1-1": "Bot Status",
        "nav-1-2": "Aufgaben, Queued",
        "nav-1-3": "Aufgaben, Finished",
        "nav-2-1": "Bot Status",
        "nav-2-2": "Einstellungen, Basic",
        "nav-2-3": "Einstellungen, Scopes",
        "nav-2-4": "Einstellungen, Rewards",
        "nav-3-1": "Bot Status",
        "nav-3-2": "Einstellungen, Basic",
        "nav-5-1": "Valky Dev",
        "nav-5-2": "Spende mir einen Tee",
        "nav-5-3": "Nutzungsbedingungen",
        "nav-5-4": "Beitreten Discord",
        "nav-5-5": "Auf Twitch anschauen",
        "nav-5-6": "Ausloggen",
        "foot-1": "2023 © Valky Dev - Alle Rechte vorbehalten. Diese Website dient ausschließlich der Bereitstellung von Informationen und der Erleichterung der Kommunikation im Zusammenhang mit Valky und den bereitgestellten Projekten.",
        "foot-2": "Nutzungsbedingungen",
        "foot-3": "Verhaltenskodex",
        "foot-4": "Inhaltsrichtlinie",
        "foot-5": "KONTAKT",
        "foot-6": "TOP",
        "error": DE_ERROR
    },
    # Russian
    "ru": {
        "lang": "ru",
        "title": "The Valkyrie Bot",
        "desc": "The Valkyrie Bot | Расширение прав и возможностей легенд игр. Выкован духом Валькирии. | ..a project by Valky",
        "nav-1": "VALKY BOT",
        "nav-2": "TWITCH BOT",
        "nav-3": "DISCORD BOT",
        "nav-5": "О НАС",
        "nav-1-1": "Bot Status",
        "nav-1-2": "Задачи, в очереди",
        "nav-1-3": "Задачи, завершено",
        "nav-2-1": "Bot Status",
        "nav-2-2": "Настройки, Basic",
        "nav-2-3": "Настройки, Scopes",
        "nav-2-4": "Настройки, Rewards",
        "nav-3-1": "Bot Status",
        "nav-3-2": "Настройки, Basic",
        "nav-5-1": "Valky Dev",
        "nav-5-2": "Пожертвовать чай",
        "nav-5-3": "Условия обслуживания",
        "nav-5-4": "Присоединиться к Discord",
        "nav-5-5": "Смотреть на Twitch",
        "nav-5-6": "Выйти",
        "foot-1": "2023 © Valky Dev - Все права защищены. Этот веб-сайт предназначен исключительно для предоставления информации и облегчения общения, связанного с Valky и предоставляемыми проектами.",
        "foot-2": "Условия обслуживания",
        "foot-3": "Кодекс поведения",
        "foot-4": "Политика использования контента",
        "foot-5": "КОНТАКТ",
        "foot-6": "ВЕРХ",
        "error": RU_ERROR
    },
    # Younger Furthark Runes
    "vk": {
        "lang": "vk",
        "title": "The Valkyrie Bot",
        "desc": "The Valkyrie Bot | ᛁᛘᛒᚬᚢᛁᚱᛁᚾᚴ ᚴᛅᛘᛁᚾᚴ ᛚᛁᚴᛁᚾᛏᛋ. ᚠᚬᚱᚴᛁᛏ ᚢᛁᚦ ᚢᛅᛚᚴᛁᚱᛁᛁ ᛋᛒᛁᚱᛁᛏ. | ..a project by Valky",
        "nav-1": "ᚢᛅᛚᚴᛁ ᛒᛟᛏ",
        "nav-2": "ᛏᚹᛁᛏᛍᚺ ᛒᛟᛏ",
        "nav-3": "ᛞᛁᛋᚲᛟᚱᛞ ᛒᛟᛏ",
        "nav-5": "ᛅᛒᚢᛏ",
        "nav-1-1": "ᛒᛟᛏ ᛋᛏᚢᛞᛁᚱ",
        "nav-1-2": "ᛏᚺᛅᚲᛋ, ᚢᚴᚢᚾᛏᛋ",
        "nav-1-3": "ᛏᚺᛅᚲᛋ, ᚠᛁᚾᛁᛋᚻᛁᛏ",
        "nav-2-1": "ᛒᛟᛏ ᛋᛏᚢᛞᛁᚱ",
        "nav-2-2": "ᛋᛏᛁᚾᚴᛁᚾᚷᛋ, ᛒᛅᛋᛁᚲ",
        "nav-2-3": "ᛋᛏᛁᚾᚴᛁᚾᚷᛋ, ᛋᚳᛟᛈᛖᛋ",
        "nav-2-4": "ᛋᛏᛁᚾᚴᛁᚾᚷᛋ, ᚱᛁᚢᛞᛋ",
        "nav-3-1": "ᛒᛟᛏ ᛋᛏᚢᛞᛁᚱ",
        "nav-3-2": "ᛋᛏᛁᚾᚴᛁᚾᚷᛋ, ᛒᛅᛋᛁᚲ",
        "nav-5-1": "ᚢᛅᛚᚴᛁ ᛏᛁᚢ",
        "nav-5-2": "ᛒᚱᛁᚾᛅᛚᛁᛅ ᛒᛁᛋᛏᛁᛋ",
        "nav-5-3": "ᛏᚢᚱᛘᛁᛋ ᚬᛋᚢᛚᛁᛅᛚᛁᛅ",
        "nav-5-4": "ᛒᚱᛁᚾᛅᛚᛁᛅ ᛒᛁᛋᛏᛁᛁᛋ",
        "nav-5-5": "ᚴᚢᚾᛏᛁᛁᛋᛁᛁᛋᛁᛁᛋ ᛒᛁᛋᛏᛁᛁᛋ",
        "nav-5-6": "ᛏᚢᛒ",
        "foot-1": "2023 © ᚢᛅᛚᚴᛁ ᛏᛁᚢ - ᛅᛚᛚ ᚱᛁᚴᚼᛏᛋ ᚱᛁᛋᛁᚱᚢᛁᛏ. ᛏᚼᛁᛋ ᚢᛁᛒᛋᛁᛏᛁ ᛁᛋ ᛁᚾᛏᛁᚾᛏᛁᛏ ᛋᚬᛚᛁᛚᛁ ᚠᚬᚱ ᚦᛁ ᛒᚢᚱᛒᚬᛋᛁ ᚬᚠ ᛒᚱᚬᚢᛁᛏᛁᚾᚴ ᛁᚾᚠᚬᚱᛘᛅᛏᚬᚾ ᛅᚾᛏ ᚠᛅᚴᛁᛚᛁᛏᛅᛏᛁᚾᚴ ᚴᚬᛘᛘᚢᚾᛁᚴᛅᛏᚬᚾ ᚱᛁᛚᛅᛏᛁᛏ ᛏᚬ ᚢᛅᛚᚴᛁ ᛅᚾᛏ ᛒᚱᚬᚢᛁᛏᛁᛏ ᛒᚱᚬᛁᛁᚴᛏᛋ.",
        "foot-2": "ᛏᚬᚱᛘᛁᛋ ᚬᛋᚢᛚᛁᛅᛚᛁᛅ",
        "foot-3": "ᛒᚱᛁᚾᛅᛚᛁᛅ ᛒᛁᛋᛏᛁᛁᛋ",
        "foot-4": "ᚴᚢᚾᛏᛁᛁᛋᛁᛁᛋᛁᛁᛋ ᛒᛁᛋᛏᛁᛁᛋ",
        "foot-5": "ᚴᚬᚾᛏᛅᚴᛏ",
        "foot-6": "ᛏᚢᛒ",
        "error": VK_ERROR
    }
}
